FranciscoFernandezN/Acme-ANS

src/main/java/acme/entities/reviews/Review.java
He creado la entidad de review, a priori creo que no debería de añadir ninguna relación más, ya que he pensado que podemos hacer que tanto la aerolínea, los vuelos y las compañías, tengan una lista de reseñas.
=> feat: Añadida la entidad de reseña

src/main/java/acme/entities/managers/Manager.java, src/main/java/acme/realms/Manager.java
He creado la entidad y me gustaría que alguien me dijera si he usado bien las anotaciones.
=> feat: Entidad managers

src/main/java/acme/entities/aircrafts/Aircraft.java, src/main/java/acme/entities/aircrafts/AircraftStatus.java
Se ha creado la entidad aeronave con sus correspondientes restricciones y relaciones.
Refs: #44
=> fix: Cambiar restricciones en la entidad aeronave

src/main/java/acme/realms/AvailabilityStatus.java, src/main/java/acme/realms/FlightCrewMember.java
He creado la entidad de los miembros de la tripulación de vuelo, y me gustaría que alguien me dijera si he usado las anotaciones correctamente.
=> feat: Añadida entidad de miembros de la tripulación de vuelo

src/main/java/acme/entities/aircrafts/Aircraft.java, src/main/java/acme/entities/airlines/Airline.java, src/main/java/acme/entities/airports/Airport.java, src/main/java/acme/entities/legs/Leg.java, src/main/java/acme/entities/legs/LegStatus.java
He creado la entidad legs, para ello he creado todos los atributos necesarios, aunque tengo cierta duda en el identificador único, ya que se requiere que sea único, pero depende de otra entidad. No sé si mi idea es la correcta o si veis alguna mejor. Por otro lado, he creado algunas entidades que aún no estaban en la rama main para poder crear las relaciones necesarias.
=> feat: Creada la entidad de legs

src/main/java/acme/entities/airlines/Airline.java, src/main/java/acme/entities/airlines/AirlineType.java
Se ha añadido la entidad Airline, la cual representa que aerolinea lleva el vuelo, esta puede ser de tres tipos diferentes y se representa en AirlineType
=> feat: :sparkles: Entidad Airline añadida

src/main/java/acme/realms/FlightCrewMember.java
He descomentado la relación con la entidad Airline, debido a que ya está creada.
Refs: #59
=> fix: Añadida la relación con Airline

src/main/java/acme/entities/bookings/Booking.java, src/main/java/acme/entities/bookings/TravelClass.java
Se ha creado la entidad booking siguiendo los requisitos dados.
Refs: #81
=> feat: :sparkles: Entidad booking creada

src/main/java/acme/realms/Technician.java
Los técnicos se ocupan del mantenimiento de las aeronaves realizando inspecciones periódicas, efectuando reparaciones y llevando a cabo otras tareas de mantenimiento.
=> feat: :sparkles: Entidad técnico añadida

src/main/java/acme/realms/AssistanceAgent.java, src/main/resources/WEB-INF/data/sample/airline.csv, src/main/resources/WEB-INF/data/sample/assistance-agent.csv, src/main/resources/WEB-INF/data/sample/user-account.csv, src/main/resources/application.properties
He creado estos datos yendo un poco a ciegas, también hay una cosa que no estoy seguro del todo de la tarea, que pone que debo crear los datos de un manager3 y creo que eso esta mal en los requisitos ya que yo no estoy encargado de ellos, por lo que lo he ignorado y he puesto lo que me ha parecido conveniente. Lo mismo que le pasa a Fran, no se puede testear porque todavía no tenemos la clase Airline.
=> feat: Creados los datos para testear la aplicación

src/main/java/acme/realms/FlightCrewMember.java
Se han modificado restricciones en la clase FlightCrewMember de forma que no haya problema al hacer los ejemplos.
Ref: #59
=> fix: Cambiar restricciones en FlightCrewMember

src/main/java/acme/realms/AssistanceAgent.java, src/main/java/acme/realms/Customer.java, src/main/resources/WEB-INF/data/sample/assistance-agent.csv, src/main/resources/WEB-INF/data/sample/customer.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
Se ha añadido el sample data de customer, además de corregir algunos bugs existentes.
Refs: #83
=> feat: :sparkles: Datos de ejemplo para customer añadidos

src/main/java/acme/entities/aircrafts/Aircraft.java
Se ha descomentado la relación @ManyToOne con la entidad Airline, con sus respectivas restricciones
Ref: #44
=> fix: Añadir la relación con Airline

src/main/java/acme/realms/FlightCrewMember.java
He añadido optional=false en la relación @ManyToOne hacia Airline.
Ref: #59
=> fix: Cambiar la relación @ManyToOne

src/main/java/acme/entities/flights/FlightAssignment.java
He añadido restricciones que faltaban.
Ref #77
=> fix: Añadir restricciones

src/main/java/acme/entities/legs/Leg.java, src/main/java/acme/forms/ManagerDashboard.java
He creado un form para los datos de los managers, el único que me chirría un poco es el Map, por lo demás, creo que debería estar todo bien.
=> feat: Añadido el dashboard para los managers

src/main/java/acme/forms/CustomerDashboard.java
Se ha creado el CustomerDashboard, el cual servirá para mostrar los datos de los customer según los requisitos dados.
Refs: #85
=> feat: :sparkles: Form para mostrar datos de customer creado

src/main/java/acme/entities/aircrafts/Aircraft.java
He limitado la capacidad máxima a 750, y he añadido @Valid al enumerado.
Ref: #44
=> fix: Limitar la capacidad máxima y añadir @Valid al enumerado

src/main/java/acme/entities/flightAssignments/CurrentStatus.java, src/main/java/acme/entities/flightAssignments/Duty.java, src/main/java/acme/entities/flightAssignments/FlightAssignment.java
He creado un paquete FlightAssignments de forma que el proyecto esté mejor estructurado, y he añadido también @Valid al enumerado.
Ref: #77
=> fix: Cambio de carpetas y añadir @Valid al enumerado

src/main/java/acme/entities/flightAssignments/FlightAssignment.java
Me he dado cuenta de que le faltaba el @Valid al enumerado CurrentStatus
Ref: #77
=> fix: Añadir @Valid a CurrentStatus

.classpath, src/main/java/acme/entities/reviews/Review.java, src/main/java/acme/features/any/review/AnyReviewController.java, src/main/java/acme/features/any/review/AnyReviewCreateService.java, src/main/java/acme/features/any/review/AnyReviewListService.java, src/main/java/acme/features/any/review/AnyReviewRepository.java, src/main/resources/WEB-INF/views/any/review/form.jsp, src/main/resources/WEB-INF/views/any/review/list.jsp, src/main/resources/WEB-INF/views/any/review/messages-en.i18n, src/main/resources/WEB-INF/views/any/review/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
He añadido la parte de reviews, la cual se puede acceder desde el menú principal. Esta tiene todos los elementos para ver y crear, aunque por ahora no gestiona paginación ya que no se ha visto en clase.
=> feat: Añadida la parte de reviews sin paginación

src/main/java/acme/constraints/SupportedCurrencyValidator.java, src/main/java/acme/constraints/ValidSupportedCurrency.java, src/main/java/acme/entities/bookings/Booking.java, src/main/java/acme/entities/flights/Flight.java, src/main/java/acme/entities/maintenancerecords/MaintenanceRecord.java, src/main/java/acme/entities/services/Service.java, src/main/java/acme/entities/supportedCurrency/SupportedCurrency.java, src/main/java/acme/features/any/supportedCurrency/AnySupportedCurrencyRepository.java, src/main/java/acme/realms/AssistanceAgent.java, src/main/java/acme/realms/FlightCrewMember.java, src/main/resources/WEB-INF/data/initial/supported-currency.csv, src/main/resources/application.properties
He añadido una nueva entidad, un nuevo validador y un nuevo fichero de populación. La nueva entidad guardará todas las monedas admitidas, el validador lo he puesto en todas las clases que usan el ValidMoney para que el Money solo incluya las monedas incluidas en el populador.
=> feat: Añadido todo lo de las divisas

src/main/java/acme/entities/reviews/Review.java, src/main/java/acme/features/any/review/AnyReviewListService.java, src/main/resources/WEB-INF/views/any/review/list.jsp, src/main/resources/WEB-INF/views/any/review/messages-en.i18n, src/main/resources/WEB-INF/views/any/review/messages-es.i18n
He añadido que salga el placedAt
=> fix: Added placedAt attribute

src/main/java/acme/constraints/SupportedCurrencyValidator.java, src/main/java/acme/entities/legs/Leg.java, src/main/java/acme/features/any/review/AnyReviewCreateService.java, src/main/java/acme/features/manager/leg/ManagerLegController.java, src/main/java/acme/features/manager/leg/ManagerLegCreateService.java, src/main/java/acme/features/manager/leg/ManagerLegDeleteService.java, src/main/java/acme/features/manager/leg/ManagerLegListService.java, src/main/java/acme/features/manager/leg/ManagerLegRepository.java, src/main/java/acme/features/manager/leg/ManagerLegShowService.java, src/main/java/acme/features/manager/leg/ManagerLegUpdateService.java, src/main/resources/WEB-INF/data/sample/leg.csv, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp, src/main/resources/WEB-INF/views/manager/leg/form.jsp, src/main/resources/WEB-INF/views/manager/leg/list.jsp, src/main/resources/WEB-INF/views/manager/leg/messages-en.i18n, src/main/resources/WEB-INF/views/manager/leg/messages-es.i18n
Estoy cansado, he hecho muchos cambios. Mírame a ver si se te ocurre alguna restricción que no esté ya.
=> feat: Añadido todo para manejar legs

src/main/java/acme/entities/flights/Flight.java, src/main/java/acme/entities/flights/FlightRepository.java, src/main/java/acme/entities/legs/Leg.java, src/main/java/acme/features/manager/flight/ManagerFlightController.java, src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java, src/main/java/acme/features/manager/flight/ManagerFlightDeleteService.java, src/main/java/acme/features/manager/flight/ManagerFlightListService.java, src/main/java/acme/features/manager/flight/ManagerFlightRepository.java, src/main/java/acme/features/manager/flight/ManagerFlightShowService.java, src/main/java/acme/features/manager/flight/ManagerFlightUpdateService.java, src/main/java/acme/features/manager/leg/ManagerLegCreateService.java, src/main/java/acme/features/manager/leg/ManagerLegDeleteService.java, src/main/java/acme/features/manager/leg/ManagerLegListService.java, src/main/java/acme/features/manager/leg/ManagerLegRepository.java, src/main/java/acme/features/manager/leg/ManagerLegShowService.java, src/main/java/acme/features/manager/leg/ManagerLegUpdateService.java, src/main/resources/WEB-INF/data/sample/flight.csv, src/main/resources/WEB-INF/data/sample/leg.csv, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp, src/main/resources/WEB-INF/views/manager/flight/form.jsp, src/main/resources/WEB-INF/views/manager/flight/list.jsp, src/main/resources/WEB-INF/views/manager/flight/messages-en.i18n, src/main/resources/WEB-INF/views/manager/flight/messages-es.i18n, src/main/resources/WEB-INF/views/manager/leg/form.jsp, src/main/resources/WEB-INF/views/manager/leg/list.jsp, src/main/resources/WEB-INF/views/manager/leg/messages-en.i18n, src/main/resources/WEB-INF/views/manager/leg/messages-es.i18n
Espero que todo funcione bien :)
=> feat: Añadidos muchas funcionalidades para flights

.classpath, src/main/java/acme/entities/airports/Airport.java, src/main/java/acme/entities/flights/Flight.java, src/main/java/acme/features/manager/dashboard/ManagerDashboardController.java, src/main/java/acme/features/manager/dashboard/ManagerDashboardRepository.java, src/main/java/acme/features/manager/dashboard/ManagerDashboardShowService.java, src/main/java/acme/forms/ManagerDashboard.java, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp, src/main/resources/WEB-INF/views/manager/manager-dashboard/form.jsp, src/main/resources/WEB-INF/views/manager/manager-dashboard/messages-en.i18n, src/main/resources/WEB-INF/views/manager/manager-dashboard/messages-es.i18n
=> feat: Manager dashboard funcionando por fin

src/main/java/acme/features/any/flight/AnyFlightController.java, src/main/java/acme/features/any/flight/AnyFlightListService.java, src/main/java/acme/features/any/flight/AnyFlightRepository.java, src/main/java/acme/features/any/flight/AnyFlightShowService.java, src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java, src/main/java/acme/features/manager/flight/ManagerFlightDeleteService.java, src/main/java/acme/features/manager/flight/ManagerFlightUpdateService.java, src/main/resources/WEB-INF/views/any/flight/form.jsp, src/main/resources/WEB-INF/views/any/flight/list.jsp, src/main/resources/WEB-INF/views/any/flight/messages-en.i18n, src/main/resources/WEB-INF/views/any/flight/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp, src/main/resources/WEB-INF/views/manager/flight/messages-es.i18n
Espero no haberme saltado ningún atributo, además, también he corregido algún que otro error que he visto de manager.flight
=> feat: Añadido ver vuelos para cualquier persona

src/main/java/acme/features/authenticated/manager/AuthenticatedManagerController.java, src/main/java/acme/features/authenticated/manager/AuthenticatedManagerRepository.java, src/main/java/acme/features/authenticated/manager/AuthenticatedManagerUpdateService.java, src/main/java/acme/realms/Manager.java, src/main/resources/WEB-INF/views/authenticated/manager/form.jsp, src/main/resources/WEB-INF/views/authenticated/manager/messages-en.i18n, src/main/resources/WEB-INF/views/authenticated/manager/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
=> feat: Añadido actualizar los datos personales managers

src/main/java/acme/features/authenticated/manager/AuthenticatedManagerController.java, src/main/java/acme/features/authenticated/manager/AuthenticatedManagerCreateService.java, src/main/java/acme/features/authenticated/manager/AuthenticatedManagerRepository.java, src/main/resources/WEB-INF/views/authenticated/manager/form.jsp, src/main/resources/WEB-INF/views/authenticated/manager/messages-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/manager/flight/form.jsp
Pues nada, he arreglado una cosilla de Flights y unos placeholders y nombres del manager profile y añadido también lo de convertirte en manager, yeeeeha, que disfrutes de recoger leña muchacho.
=> feat: Añadido para convertirte en manager

src/main/java/acme/entities/passengers/Passenger.java, src/main/java/acme/features/customer/passenger/CustomerPassengerController.java, src/main/java/acme/features/customer/passenger/CustomerPassengerCreateService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerListService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerRepository.java, src/main/java/acme/features/customer/passenger/CustomerPassengerShowService.java, src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java, src/main/resources/WEB-INF/data/sample/passenger.csv, src/main/resources/WEB-INF/views/customer/passenger/form.jsp, src/main/resources/WEB-INF/views/customer/passenger/list.jsp, src/main/resources/WEB-INF/views/customer/passenger/messages-en.i18n, src/main/resources/WEB-INF/views/customer/passenger/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
Se han añadido el listado, mostrado de detalles, creación y actualización de pasajeros por parte de los clientes.
Para usarlo, registrarse como algún customer y trastear en la parte de ver pasajeros / crear pasajeros.
Refs: #190
=> feat: :sparkles: Operaciones de los clientes en los pasajeros añadidas

src/main/java/acme/features/administrator/booking/AdministratorBookingController.java, src/main/java/acme/features/administrator/booking/AdministratorBookingListService.java, src/main/java/acme/features/administrator/booking/AdministratorBookingRepository.java, src/main/java/acme/features/administrator/booking/AdministratorBookingShowService.java, src/main/resources/WEB-INF/views/administrator/booking/form.jsp, src/main/resources/WEB-INF/views/administrator/booking/list.jsp, src/main/resources/WEB-INF/views/administrator/booking/messages-en.i18n, src/main/resources/WEB-INF/views/administrator/booking/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
Se ha añadido la funcionalidad de que un administrador pueda visualizar las reservas publicadas y los pasajeros de estas, además de otros detalles.
Refs: #194
=> feat: :sparkles: Operaciones de los administradores en reservas añadidas

README.txt, src/main/resources/WEB-INF/data/sample/service.csv, src/main/resources/WEB-INF/views/fragments/footer.jsp
Se ha añadido un enlace al OneDrive proporcionado por la universidad en el que se testea el requisito 14 grupal (operaciones de cualquiero usuario en servicios, es decir, visualización de una de sus imágenes en el pie de página).
Para testear esto, visualizar el vídeo subido en el readme y ver que se muestra correctamente [el requisito grupal 14](https://github.com/FranciscoFernandezN/Acme-ANS/issues/176).
Refs: #183
=> docs: :memo: Añadido enlace del testeo del requisito 14

src/main/java/acme/entities/services/Service.java, src/main/java/acme/features/any/service/AnyServiceController.java, src/main/java/acme/features/any/service/AnyServiceListService.java, src/main/java/acme/features/any/service/AnyServiceRepository.java, src/main/java/acme/features/any/service/AnyServiceShowService.java, src/main/resources/WEB-INF/views/any/service/form.jsp, src/main/resources/WEB-INF/views/any/service/list.jsp, src/main/resources/WEB-INF/views/any/service/messages-en.i18n, src/main/resources/WEB-INF/views/any/service/messages-es.i18n, src/main/resources/WEB-INF/views/fragments/menu-en.i18n, src/main/resources/WEB-INF/views/fragments/menu-es.i18n, src/main/resources/WEB-INF/views/fragments/menu.jsp
Ni lo he ejecutado, he confiado en mí mismo
=> feat: Añadido ver servicios

src/main/resources/WEB-INF/views/fragments/menu.jsp
He corregido una cosa del menú.
Ref: #231
=> fix: Poner bien el menú

src/main/resources/WEB-INF/data/sample/aircraft.csv, src/main/resources/WEB-INF/data/sample/flight-assignment.csv, src/main/resources/WEB-INF/data/sample/flight-crew-member.csv, src/main/resources/WEB-INF/data/sample/user-account.csv
He modificado los datos de algunos csv para considerar límites y caracteres extraños.
=> fix: Arreglar formato de los datos de los csv

src/main/java/acme/entities/claims/Claim.java, src/main/java/acme/entities/trackinglogs/TrackingLog.java, src/main/java/acme/features/assistanceAgent/trackingLog/AssistanceAgentTrackingLogDeleteService.java, src/main/java/acme/features/assistanceAgent/trackingLog/AssistanceAgentTrackingLogUpdateService.java, src/main/resources/WEB-INF/data/sample/airport.csv, src/main/resources/WEB-INF/data/sample/claim.csv, src/main/resources/WEB-INF/data/sample/tracking-log.csv, src/main/resources/WEB-INF/views/administrator/tracking-log/messages-es.i18n
Aqui deberia de estar todo ya bien incluido, tanto de los CSVs como lo del post hacking y los índces
=> CSVs Manu, índices y arreglo del post hacking

src/main/java/acme/entities/bookings/BelongsTo.java, src/main/java/acme/entities/bookings/Booking.java, src/main/java/acme/entities/recommendations/Recommendation.java, src/main/java/acme/features/administrator/recommendation/AdministratorRecommendationController.java, src/main/java/acme/features/administrator/recommendation/AdministratorRecommendationRepository.java
Se han añadido los índices del estudiante 2. Además se han hecho un par de modificaciones que no alteran el funcionamiento del código, solo que queda más bonito y lo optimiza un poco.
Refs: #277
=> feat: :sparkles: Índices del e2 añadidos

src/main/java/acme/features/administrator/aircraft/AdministratorAircraftCreateService.java, src/main/java/acme/features/administrator/aircraft/AdministratorAircraftDisableService.java, src/main/java/acme/features/administrator/aircraft/AdministratorAircraftShowService.java, src/main/java/acme/features/administrator/aircraft/AdministratorAircraftUpdateService.java
He arreglado el post hacking en el show, de forma que salte un is not authorised.
=> fix: Arreglar post hacking

README.txt, src/main/java/acme/features/manager/leg/ManagerLegListService.java, src/main/resources/WEB-INF/views/any/leg/list.jsp
=> feat: Video requisitos E1
